name: Pull Request CI - Basic tests
permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Shallow clones disabled for a better SonarQube analysis
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/configuration-cache
          key: ${{ runner.os }}-gradle-ci-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Firebase config
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/src/google-services.json

      - name: Create dummy google-services.json for Dependabot
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: |
          cat <<EOF > app/src/google-services.json
          {
            "project_info": {
              "project_number": "1234567890",
              "project_id": "dummy-project"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:1234567890:android:abcdef",
                  "android_client_info": {
                    "package_name": "co.sorsby.tools"
                  }
                },
                "api_key": [
                  {
                    "current_key": "dummy-key"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
